2024-07-28 01:43:17,123 INFO     flight_viewset.py              create                         17   Create request received with data: {'flight_id': 'FL123', 'airline': 'Air India', 'departure_city': 'New Delhi', 'arrival_city': 'Mumbai', 'departure_schedule': '2024-08-01T10:30:00Z', 'arrival_schedule': '2024-08-01T12:30:00Z', 'flight_duration': '2 hours', 'seats_available': {'economy': 150, 'business': 30, 'first_class': 10}}
2024-07-28 01:43:17,196 ERROR    flight_viewset.py              create                         30   An error occurred: one of the hex, bytes, bytes_le, fields, or int arguments must be given
2024-07-28 01:45:03,683 INFO     flight_viewset.py              create                         17   Create request received with data: {'flight_id': 'FL123', 'airline': 'Air India', 'departure_city': 'New Delhi', 'arrival_city': 'Mumbai', 'departure_schedule': '2024-08-01T10:30:00Z', 'arrival_schedule': '2024-08-01T12:30:00Z', 'flight_duration': '2 hours', 'seats_available': {'economy': 150, 'business': 30, 'first_class': 10}}
2024-07-28 01:45:03,769 INFO     flight_viewset.py              create                         22   Flight entry created successfully: {'id': '978fc5b3-73c5-441d-9bf0-a3f54b29b728', 'flight_id': 'FL123', 'airline': 'Air India', 'departure_city': 'New Delhi', 'arrival_city': 'Mumbai', 'departure_schedule': '2024-08-01T10:30:00Z', 'arrival_schedule': '2024-08-01T12:30:00Z', 'flight_duration': '2 hours', 'seats_available': {'economy': 150, 'business': 30, 'first_class': 10}, 'created_at': '2024-07-27T20:15:03.762958Z', 'updated_at': '2024-07-27T20:15:03.762958Z', 'deleted_at': None, 'status': None}
2024-07-28 01:53:26,092 INFO     flight_viewset.py              create                         19   Create request received with data: {'flight_id': 'FL123', 'airline': 'Air India', 'departure_city': 'New Delhi', 'arrival_city': 'Mumbai', 'departure_schedule': '2024-08-01T10:30:00Z', 'arrival_schedule': '2024-08-01T12:30:00Z', 'flight_duration': '2 hours', 'seats_available': {'economy': 150, 'business': 30, 'first_class': 10}}
2024-07-28 01:53:26,180 INFO     flight_viewset.py              create                         24   Flight entry created successfully: {'id': 'fdb17fb9-b180-4eac-af49-0c12d996a07c', 'flight_id': 'FL123', 'airline': 'Air India', 'departure_city': 'New Delhi', 'arrival_city': 'Mumbai', 'departure_schedule': '2024-08-01T10:30:00Z', 'arrival_schedule': '2024-08-01T12:30:00Z', 'flight_duration': '2 hours', 'seats_available': {'economy': 150, 'business': 30, 'first_class': 10}, 'created_at': '2024-07-27T20:23:26.169458Z', 'updated_at': '2024-07-27T20:23:26.169458Z', 'deleted_at': None, 'status': 0}
2024-07-28 23:37:44,860 INFO     login_viewset.py               sign_up                        105  Email is missing from the sign-up request.
2024-07-28 23:39:21,744 INFO     login_viewset.py               sign_up                        105  Email is missing from the sign-up request.
2024-07-28 23:40:23,592 INFO     login_viewset.py               sign_up                        105  Email is missing from the sign-up request.
2024-07-28 23:40:27,780 INFO     login_viewset.py               sign_up                        105  Email is missing from the sign-up request.
2024-07-28 23:42:20,961 ERROR    login_viewset.py               sign_up                        161  An error occurred during sign-up: Cannot resolve keyword 'email' into field. Choices are: created_at, deleted_at, email_id, first_name, id, last_name, password, status, status_id, updated_at, user_details
2024-07-28 23:43:39,355 INFO     login_viewset.py               sign_up                        129  Password validation failed for email: john.doe@example.com
2024-07-28 23:43:52,959 INFO     login_viewset.py               sign_up                        152  User successfully registered: john.doe@example.com
2024-07-28 23:44:53,408 ERROR    login_viewset.py               login                          81   An error occurred during login: Cannot resolve keyword 'email' into field. Choices are: created_at, deleted_at, email_id, first_name, id, last_name, password, status, status_id, updated_at, user_details
2024-07-28 23:45:19,532 ERROR    login_viewset.py               login                          81   An error occurred during login: Cannot resolve keyword 'email' into field. Choices are: created_at, deleted_at, email_id, first_name, id, last_name, password, status, status_id, updated_at, user_details
2024-07-28 23:46:17,863 ERROR    login_viewset.py               login                          81   An error occurred during login: too many values to unpack (expected 2)
2024-07-28 23:48:12,886 ERROR    login_viewset.py               login                          81   An error occurred during login: too many values to unpack (expected 2)
2024-07-28 23:49:31,805 ERROR    login_viewset.py               login                          82   An error occurred during login: too many values to unpack (expected 2)
2024-07-28 23:50:26,583 ERROR    login_viewset.py               login                          82   An error occurred during login: too many values to unpack (expected 2)
2024-07-28 23:52:03,269 ERROR    login_viewset.py               login                          82   An error occurred during login: too many values to unpack (expected 2)
2024-07-28 23:52:55,664 ERROR    login_viewset.py               login                          83   An error occurred during login: 'str' object has no attribute 'id'
2024-07-28 23:53:18,929 ERROR    login_viewset.py               login                          83   An error occurred during login: 'str' object has no attribute 'id'
2024-07-28 23:54:19,381 ERROR    login_viewset.py               login                          83   An error occurred during login: 'str' object has no attribute 'id'
2024-07-28 23:55:06,103 ERROR    login_viewset.py               login                          84   An error occurred during login: 'str' object has no attribute 'id'
2024-07-28 23:55:47,271 ERROR    login_viewset.py               login                          84   An error occurred during login: 'str' object has no attribute 'id'
2024-07-28 23:57:25,288 ERROR    login_viewset.py               login                          84   An error occurred during login: No user found with this email address
2024-07-28 23:58:05,862 ERROR    login_viewset.py               login                          84   An error occurred during login: 'User' object has no attribute 'role'
2024-07-28 23:58:22,255 INFO     login_viewset.py               login                          69   User authenticated successfully: john.doe@example.com
